capture log close
clear


 use "D:\Dropbox\WB-Tunisia-CWLP-IE\14. Female Entrepreneurship Add on\Data\Second round\cleandata\clean_CashXFollow_noPII.dta"  
 *\\--- INPUT YOUR WORKING DIRECTORY 


* Since it has the vars I drop them and do again

foreach i of varlist b3_foodtype_1-b3_foodtype_0{
drop `i'
}




*--------------------------------------------------------------------------------
*Cleaning for multiple response questions
*--------------------------------------------------------------------------------
/*For questions in which multiple options can be selected, Survey CTO stores the 
answers in the form of a space-separated array of all the option codes that were
selected by the respondent. For instance if the surveyor chooses options 1, 2 
and 4, then the array will be saved as [1 2 4]. This array appears as a string
on STATA and needs to be split up into its components, and converted to 
dummy variables for each individual option for analysis.*/ 

	*B3_Foodtype
		
		
		*Split the space-separated array
		split b3_foodtype,gen(b3_1_status) destring
		//splits the space separated array into its constitutents
		//saves in multiple variables named c1_1_status1, c1_1_status2 etc. 
		//9 options available for this question. 
		//Therefore, up to 9 variables will be created going up to c1_1_status9
		
		*Create dummy variables for each option
		forvalues b11x=1/11 	///				loop over valid answer options for this question (not incl -999)
		{	
			gen b3_1_dummy`b11x'=.					
			forvalues b11y=1/11  ///			loop over vars generated by split
			{
				capture confirm variable b3_1_status`b11y' //number of variables created by the split 
														   //question is dependent on the number of options
														   //a respondent chooses at the same time 
				
				if !_rc {
							replace b3_1_dummy`b11x'=1 if ///
							b3_1_status`b11y'==`b11x'
												
						}
			}
		}
		
		*Drop the containers generated by the split function
		drop b3_1_status*

