* ===================================================================================
* TASK 1

capture log close
clear

 use "D:\Documents\World Bank\4. Tunisia - Female Entrepreneurship\Data Analysis\clean_data_8-2.dta"
 
 
 *====================================================================================
 * Since this clean data already has the columns from before, I am going to go ahead and delete them
 * first I will delete them one by one. and then i will create a loop and try deleting them all at once
 
 
 * drop b3_foodtype_1
 
 foreach i of varlist b3_foodtype_1-b3_foodtype_0{
drop `i'
}



** Now I am going to code for the same column and make it into multiple columns.
*--------------------------------------------------------------------------------
* Cleaning for multiple response questions
*--------------------------------------------------------------------------------
/*For questions in which multiple options can be selected, Survey CTO stores the 
answers in the form of a space-separated array of all the option codes that were
selected by the respondent. For instance if the surveyor chooses options 1, 2 
and 4, then the array will be saved as [1 2 4]. This array appears as a string
on STATA and needs to be split up into its components, and converted to 
dummy variables for each individual option for analysis.*/ 

	*B3 - Foodtype
		
		*Split the space-separated array
		split b3_foodtype,gen(b3_1_status) destring
		//splits the space separated array into its constitutents
		//9 options available for this question. 
		//Therefore, up to 9 variables will be created going up to c1_1_status9
		
		*Create dummy variables for each option
		forvalues b11x=0/11 	///				
		{	
			gen b3_1_dummy`b11x'= 0 if missing(b3_foodtype) == 0			// generating empty container							
			forvalues b11y=0/11  ///			loop over vars generated by split
			{
				capture confirm variable b3_1_status`b11y' //number of variables created by the split 
														//question is dependent on the number of options
														//a respondent chooses at the same time 
				
				if !_rc {
							replace b3_1_dummy`b11x'=1 if ///
							b3_1_status`b11y'==`b11x'
												
						}
			}
		}
		
		*Drop the containers generated by the split function
		drop b3_1_status*

